apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: log-message-processor
  name: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: log-message-processor
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/microservice-app-example-default: "true"
        io.kompose.service: log-message-processor
    spec:
      containers:
        - env:
            - name: REDIS_CHANNEL
              value: log_channel
            - name: REDIS_HOST
              value: redis-queue
            - name: REDIS_PORT
              value: "6379"
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v1/spans
          image: thesis/log-message-processor
          name: log-message-processor
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "500m"
              memory: "300Mi"
      restartPolicy: Always
