 apiVersion: v1
 kind: Pod
 metadata:
   name: pod-blocked
   labels:
     owner: me.agilebank.demo
 spec:
   containers:
     - name: bad-container-limits
       image: thesis/auth-api
       args:
         - "run"
         - "--server"
         - "--addr=localhost:8080"
       resources:
         limits:
           cpu: "500m"
           memory: "2Gi"
