apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-queue
  name: redis-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-queue
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-queue
    spec:
      containers:
        - image: redis
          name: redis-queue
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
      restartPolicy: Always
status: {}
