apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: users-api
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: users-api
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: myfancysecret
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
          image: thesis/users-api
          name: users-api
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "3000m"
              memory: "1000Mi"
      restartPolicy: Always
status: {}
