apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: AUTH_API_ADDRESS
              value: http://auth-api:8081
            - name: PORT
              value: "8080"
            - name: TODOS_API_ADDRESS
              value: http://todos-api:8082
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v2/spans
          image: gcr.io/allowedproject/
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "50m"
              memory: "2Gi"
      restartPolicy: Always
status: {}
