 apiVersion: v1
 kind: Pod
 metadata:
   name: limits-allowed
   labels:
     owner: me.agilebank.demo
 spec:
   containers:
     - name: good-container-limits
       image: openpolicyagent/opa:0.9.2
       args:
         - "run"
         - "--server"
         - "--addr=localhost:8080"
       resources:
         limits:
           cpu: "100m"
           memory: "100Mi"